# Generated by Django 5.0 on 2025-12-26 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="User's email address for response", max_length=255)),
                ('name', models.CharField(blank=True, help_text="User's name (optional)", max_length=255)),
                ('subject', models.CharField(blank=True, help_text='Subject of the inquiry', max_length=255)),
                ('message', models.TextField(help_text="User's query or message to the company")),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', help_text='Current status of the inquiry', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the contact form was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this record was updated')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the inquiry was resolved', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the submitter (for spam prevention)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent (for spam prevention)')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'db_table': 'contact_submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='contact_sub_email_903821_idx'), models.Index(fields=['status'], name='contact_sub_status_88fb2c_idx'), models.Index(fields=['-created_at'], name='contact_sub_created_022c3a_idx')],
            },
        ),
    ]
